### PR TITLE
Dockerfile

### PR DESCRIPTION
**Pull request by cmkobel**
Hi Kai

I made a Dockerfile for lazy people.

We have a cluster setup where it is often easier to have a complete docker-image instead of managing updates, installs and dependencies manually.

With this docker-image, running the latest version of your software on any system is now as easy as writing `singularity run docker://cmkobel/covid-spike-classification covid-spike-classification --help` or
`docker run cmkobel/covid-spike-classification covid-spike-classification --help`

Of course you're welcome to clone the docker repo, so it shows your name instead of mine.

If you are interested, you're very welcome to pull my fork.

Kind regards, Carl from KMA AUH.

### CODE REVIEW

**Review by kblin — APPROVED** [review]
Looks good to me 👍

**Comment by kblin** [comment]
Thanks for the PR!

**Comment by cmkobel** [comment]
Cool. Thanks for for pulling.
Will you take over the docker repo, so it triggers on your git pushes?

**Comment by kblin** [comment]
Uh, sure, I guess that makes sense. Let me figure out how the auto-building works, I've never used that before.

**Comment by kblin** [comment]
There we go.

**Pull request merged**
